name: Shorebird OTA Patch

on:
  workflow_dispatch: {}

jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # Install Shorebird CLI and add to PATH (no "version" input)
      - name: Setup Shorebird
        uses: shorebirdtech/setup-shorebird@v1
        with:
          cache: true

      - name: Verify Shorebird
        run: |
          which shorebird
          shorebird --version

      - name: Create OTA patch
        env:
          SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
        run: |
          # Patch the latest Shorebird release for this app (recommended)
          shorebird patch android --release-version=latest --no-confirm
          # If you need a specific version instead, comment the line above and use:
          # shorebird patch android --release-version "1.0.2+4" --no-confirm
