name: Shorebird OTA Patch

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version to patch (default: current)"
        required: false
        default: "current"
        type: string

jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.24.0"

      - name: Setup Shorebird
        uses: shorebirdtech/setup-shorebird@v1
        with:
          version: latest

      - name: Verify Shorebird
        run: |
          which shorebird
          shorebird --version

      - name: Create OTA patch
        env:
          SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
        run: |
          shorebird patch android --force --release-version ${{ inputs.release_version }}
